Sushi/Controllers/SushiController.cs
using Microsoft.AspNetCore.Mvc;
using Sushi.Data;
using Sushi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sushi.Controllers
{
    public class SushiController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SushiController(ApplicationDbContext _db)
        {
            this._db = _db;
        }
        public IActionResult Index()
        {
            List<SushiEntity> Sushies  = new List<SushiEntity>(_db.Sushi); 
            return View(Sushies);
        }
        [HttpGet]
        public IActionResult Index(string search)
        {
            List<SushiEntity> Sushies = null;
            if (search != null)
                Sushies = new List<SushiEntity>(_db.Sushi.Where(x => x.Name.Contains(search)));
            else
                Sushies  = new List<SushiEntity>(_db.Sushi);

            return View(Sushies);
           
        }
        //public IActionResult Index(string searchInfo)
        //{
        //    List<SushiEntity> Sushies = new List<SushiEntity>(_db.Sushi);
        //    return View(Sushies);
        //}

        public IActionResult Show(int Id)
        {
            SushiEntity Sushi = _db.Sushi.Find(Id);
            return View(Sushi);
        }
    }
}

Sushi/Views/Sushi/Index.cshtml
@model List<SushiEntity>


@{
    ViewData["Title"] = "Sushies🍣";
}

<html>


<head>
    <script src="https://kit.fontawesome.com/a22ee8e4c0.js" crossorigin="anonymous"></script>
    <script>document.getElementsByClassName("nav_element").item(1).style.borderBottom = "0.3rem groove  #ffd800"</script>
</head>
<body>

    <br /> <br /><br />
    <h1 class="page_big_name">Best Sushi Ever</h1>
    @*<form method="get">
            <div style="position:fixed; z-index:10;">
                <input class="search" id="search" name="search" type="text" placeholder="Search...">
                <a asp-controller="Sushi" asp-action="Index" type="submit" class="search_btn"><i type="submit" class="fas fa-search"></i></a>
            </div>
        </form>*@

    @using (@Html.BeginForm("Index", "Sushi", FormMethod.Get))
    {
        @*@Html.TextBox("search")*@
        <div style="position:fixed; z-index:10;">
            <input class="search" id="search" name="search" type="text" placeholder="Search...">
            <input class="search_btn" type="submit" value="&#128269;"/>
        </div>
        

    }
    @if (Model.Count == 0)
    {

        <h1 style="position:absolute; top:100px; right:200px; color:aqua ">No sushi exist</h1> }
    else
        @for (int i = 0; i < (Model.Count % 4 == 0 ? Model.Count() / 4 : Model.Count / 4 + 1); i++)
        {
            <div class="sushi4container">
                @for (int j = 0; j < 4 && j + 4 * i < Model.Count(); j++)
                {
                    <div class="sushi_container run_animation">
                        <a asp-controller="Sushi" asp-action="Show" asp-route-Id="@Model[j+4*i].Id">
                            <img src='/pics/@Model[j+4*i].ImageName' alt="Sushi" class="sushi_img">
                            <span class="sushi_name"> @Model[j + 4 * i].Name</span>
                            <br />
                            @if (Model[j + 4 * i].IsOnSale)
                            {
                                <span class="sushi_sale_price"> @Model[j + 4 * i].Price grn</span>
                            }
                            else
                            {
                                <span class="sushi_price"> @Model[j + 4 * i].Price grn</span>
                            }
                            <div class="sushi_description">
                                @Model[j + 4 * i].Description
                            </div>
                        </a>
                    </div>
                }
            </div>
            <br />
        }

</body>
</html>

Sushi/Views/Sushi/Show.cshtml
@model SushiEntity
@{
    ViewData["Title"] = Model.Name;
}
<script src="https://kit.fontawesome.com/a22ee8e4c0.js" crossorigin="anonymous"></script>
<script>document.getElementsByClassName("nav_element").item(1).style.borderBottom = "0.3rem groove  #ffd800"</script>
<h1>Show</h1>

@if (Model != null) { 
<div class="selected_sushi">
    <img src='/pics/@Model.ImageName' alt="Sushi" class="sushi_img">
    <span class="sushi_name"> @Model.Name</span>
    <br />
    @if (Model.IsOnSale)
    {
        <span class="sushi_sale_price"> @Model.Price grn</span>
    }
    else
    {
        <span class="sushi_price"> @Model.Price grn</span>
    }
    <br />
    <div class="sushi_description">
        @Model.Description
    </div>
    <br />  
    <div class="sushi_buttons_container">
            <a class="heart_btn" href="#"> <i class="fas fa-heart"></i></a>
            <a class="cart_wheel_btn" href="#"> <i class="fas fa-shopping-cart"></i></a>
    </div>
 
</div>
    }
else
 {
<h1 style="color: #ff0000;text-align:center;background-color:burlywood">
    There is no sushi babygirl
</h1>

 }