Sushi/Models/CreateRoleViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Sushi.Models
{
    public class CreateRoleViewModel
    {   
       [Required]
       public string RoleName { get; set; } 
    }
}

Sushi/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Sushi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sushi.Controllers
{
    [Authorize(Roles ="Admin")] 
   public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager,UserManager<User> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRoleAsync(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var res = await roleManager.CreateAsync(new IdentityRole { Name = model.RoleName });
                if(res.Succeeded)
                    return RedirectToAction("index");
                foreach (var error in res.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
           
            return View(model);
        }
        [HttpGet]
        public IActionResult Index()
        {
            var roles = roleManager.Roles;

            return View(roles);
        }   
        public async Task<IActionResult> DeleteAsync(string Id)
        {
            var res = await roleManager.DeleteAsync(roleManager.Roles.Where(x=>x.Id==Id).First());
            if (res.Succeeded)
            {
                return RedirectToAction("index");
            }
            return RedirectToAction("home");
        }
       [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
          // Find the role by Role ID
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            // Retrieve all  Users
            foreach (var user in userManager.Users)
            {
                // If the user is in this role, add the username to
                // Users property of EditRoleViewModel. This model
                // object is then passed to the view for display
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        // This action responds to HttpPost and receives EditRoleViewModel
        [HttpPost]
        public async Task<IActionResult> Edit(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                // Update the Role using UpdateAsync
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string Id)
        {
            ViewBag.roleId = Id;

            var role = await roleManager.FindByIdAsync(Id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with {Id} is not found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();
            foreach (var user in userManager.Users)
            {
                model.Add(new UserRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = await userManager.IsInRoleAsync(user, role.Name)

                }
                );
            }
            return View(model);

        }
        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string Id)
        {
            var role = await roleManager.FindByIdAsync(Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {Id} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("Edit", new { Id = Id });
                }
            }

            return RedirectToAction("Edit", new { Id = Id });
        }
    }
}

Sushi/Views/Administration/CreateRole.cshtml
@model CreateRoleViewModel
<form method="post" asp-controller="Administration" asp-action="CreateRole">
    <br /><br /><br />
    <div class="register_form">
        <h1 id="h1reg">Creating Role</h1>
        <img src="/pics/register.jpg" id="register_img" alt="Alternate Text" />
        <div class="part_register">
            <div>
                <label asp-for="RoleName"></label>
            </div>
            <div>
                <input class="input_field" asp-for="RoleName" />
            </div>
            <span asp-validation-for="RoleName" style="font-size:small; color:red;background-color:chocolate;"></span>
        </div>
      
        @*<div class="ValidationDiv" asp-validation-summary="All"></div>*@

        <input type="submit" class="create_btn" value="Create" />
        <a asp-controller="Home" asp-action="Index" class="back_btn">Back</a>

    </div>
</form>

Sushi/Views/Administration/Edit.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Edit Role";
}
<link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<h1 style="color:#ff6a00; background-color:#000000;border-radius:3%;">Edit Role</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label style="color:#ff6a00; background-color:#000000;border-radius:3%;" asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label style="color: #ff6a00; background-color:#000000; border-radius: 3%;" asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control">
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger" style="background-color:black"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Users in this role</h3>
        </div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-Id="@Model.Id" class="btn btn-primary" style="width:auto">Add or remove users</a>
        </div>
    </div>
</form>

Sushi/Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel> 
@{  
    var roleId = ViewBag.roleId;
}
<link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<form  method="post">
    <div class="card">
        <div class="card-header">
            <h2>Add or remove users from this role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
            <div class="form-check m-1">
                <input type="hidden" asp-for="@Model[i].UserName" /> @*this unputs needed to populate id and name*@
                <input type="hidden" asp-for="@Model[i].UserId" />
                <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                <label asp-for="@Model[i].IsSelected" class="form-check-label"> @Model[i].UserName</label>
            </div>
            }
        
        </div>         
        <div class="card-footer">
            <input type="submit"  value="Update" class="btn btn-primary" style="width:auto" />
            <a asp-action="Edit" asp-route-id="@roleId" class="btn btn-primary" style="width:auto"> Cancel</a>
        </div>
    </div>
</form>

Sushi/Views/Administration/Index.cshtml
@model IEnumerable<IdentityRole>
@{ ViewBag.Title = "Roles";
}
<style>
    .add_new_role_btn {
        cursor: pointer;
        background-color: #ff2700;
        color: black;
        border: solid 0.1rem #000000;
        border-radius: 15%;
        font-size: 1rem;
        font-family: 'Permanent Marker',cursive;
        box-shadow: 0 0.2rem #999;
        margin-top:10vh;
    }

        .add_new_role_btn:hover {
            background-color: #ff6a00;
        }

        .add_new_role_btn:active {
            background-color: #3e8e41;
            box-shadow: 0 0 #666;
            transform: translateY(4px);
        }

    .role_card {
        background-color: #e12900;
        margin-top: 3rem;
        color: #000000;
        border:thick 0.1rem #ff0000;
        border-radius:5%;
        font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        font-size:1rem;
        padding-left:0.5rem;
    }
</style>
@if (Model.Any())
{
<br /><br /><br />
    <a class="add_new_role_btn"  asp-action="CreateRole"
       asp-controller="administration">Add new role</a>

    foreach (var role in Model)
    {
        <div class="role_card" >
            <div style="font-size:0.8rem;">
                Role Id : @role.Id
            </div>
            <div>
                <h5 style="font-size:1rem">@role.Name</h5>
            </div>
            <div>
                <a asp-controller="Administration" asp-action="Delete" asp-route-id="@role.Id" class="back_btn" style="position:static">Delete</a>
                <a asp-controller="Administration" asp-action="Edit" asp-route-id="@role.Id" class="back_btn" style="position:static"><i class="far fa-edit"></i>Edit</a>
            </div>
        </div>
    }
}

else
{
    <div class="card">
        <div class="card-header">
            No roles created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a role
            </h5>
            <a class="btn btn-primary" style="width:auto"
               asp-controller="administration" asp-action="CreateRole">
                Create Role
            </a>
        </div>
    </div>
}